import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { FileContextProvider } from "@/context/FileContext";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Javalyze",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={rubik.className}>
        <FileContextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </FileContextProvider>
      </body>
    </html>
  );
}
